import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClientNestedContext } from './components/client/client-nested-context'
import { ClientButton } from './components/client/client-button'
import { ServerNestedContext } from './components/server/server-nested-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ border: '1px solid blue', padding: 5, marginBottom: 10 }}>
          <h3>Root Layout</h3>
        
          <ClientNestedContext>
            <ClientButton />
          </ClientNestedContext>

          <ServerNestedContext>
            <ClientButton />
          </ServerNestedContext>
        </div>
        
        {children}
      </body>
    </html>
  )
}
